### ISSUE TITLE
Package and publish a release on PyPI

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode.io-pipeline-glc_scan#2]
See https://packaging.python.org/tutorials/packaging-projects/

**Comment by AvishrantsSh** [comment]
Isn't there an extra **io** in the repo name? Should I change that?

**Comment by tdruez** [comment]
@AvishrantsSh yes, I've renamed the repo. Thanks!

**Comment by AvishrantsSh** [comment]
I was still editing my comment but lost track of it when you commented 😅.
I was thinking that maybe we should have the same names for the actual module and the repo name perhaps? 

Since `.` and `-` are not allowed in entry points, maybe a name like `scancodeio-glc-plugin`?

**Comment by tdruez** [comment]
I think the current repo name is fine ;)

@pombredanne what's your take?

**Comment by AvishrantsSh** [comment]
> I think the current repo name is fine ;)

Well then, we are good to go!

**Comment by AvishrantsSh** [comment]
@tdruez I'm having some issues while uploading to PyPI.
Basically, PyPI does not allow external URLs to be listed as a dependency, which results in the following error
```sh
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: "scancodeio @ git+https://github.com/nexb/scancode.io.git ; extra == 'testing'"
```

**Comment by tdruez** [comment]
@AvishrantsSh let me check with @pombredanne on this and get back to you with a solution.

**Comment by pombredanne** [comment]
@AvishrantsSh Can you try this in an extra_requires instead?

**Comment by AvishrantsSh** [comment]
No luck so far :(
There doesn't seem to be any good way to handle this kind of packaging. However, we can use some sort of **post-installation script** while setup to install the scancode.io instance.

What's your take on this? @pombredanne @tdruez 

Is there a possibility to upload scancode.io to PyPI? It will greatly simplify the packaging process.

**Comment by tdruez** [comment]
@AvishrantsSh let's remove scancode.io from the "setup" dependencies and add a `pip install` step in the github action CI.

**Comment by AvishrantsSh** [comment]
@tdruez @pombredanne it finally worked :)

The plugin is available at https://test.pypi.org/project/scancodeio-glc-plugin/0.0.1/.

However, there are still some points that I want to discuss. Can we have a session for that? Or shall we proceed with issues and tickets for the time being?

**Comment by AvishrantsSh** [comment]
> @AvishrantsSh let's remove scancode.io from the "setup" dependencies and add a `pip install` step in the github action CI.

For the time being, I placed it in `configure` as scancode.io is also required for development.

**Comment by tdruez** [comment]
@AvishrantsSh I would keep it outside of `configure` as it is not meant to be modified, it is a common script shared between our repos.
Instead, add it as a new step in the Dev README documentation after `./configure --dev`

**Comment by tdruez** [comment]
> Can we have a session for that? 

Sure, let's organize it on the chat.

**Comment by AvishrantsSh** [comment]
All Done :)
